'''
config.py
Author: maia.advance, maymeridian
Description: Centralized configuration for paths, model parameters, and physical constants.
'''

import os

# -----------------------------------------------------------------------------
# 1. PROJECT STRUCTURE
# -----------------------------------------------------------------------------

# Root directory of the project
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Primary subdirectories
DATA_DIR = os.path.join(BASE_DIR, 'datasets')
MODELS_DIR = os.path.join(BASE_DIR, 'models')
RESULTS_DIR = os.path.join(BASE_DIR, 'results')

# Ensure essential directories exist immediately
for directory in [DATA_DIR, MODELS_DIR, RESULTS_DIR, RESULTS_DIR]:
    os.makedirs(directory, exist_ok=True)

# -----------------------------------------------------------------------------
# 2. DATA PATHS (ABSOLUTE)
# -----------------------------------------------------------------------------

# Logs (Metadata)
TRAIN_LOG_PATH = os.path.join(DATA_DIR, 'train_log.csv')
TEST_LOG_PATH = os.path.join(DATA_DIR, 'test_log.csv')

# Processed/Combined Data (The "All" files generated by data_loader)
TRAIN_DATA_PATH = os.path.join(DATA_DIR, 'train_all_full_lightcurves.csv')
TEST_DATA_PATH = os.path.join(DATA_DIR, 'test_all_full_lightcurves.csv')

# -----------------------------------------------------------------------------
# 3. MODEL ARTIFACTS
# -----------------------------------------------------------------------------

# The active production model
MODEL_PATH = os.path.join(MODELS_DIR, 'tde_classifier.pkl')

# Score tracking
SCORE_PATH = os.path.join(MODELS_DIR, 'latest_score.txt')

# -----------------------------------------------------------------------------
# 4. SCIENCE & PHYSICS CONSTANTS
# -----------------------------------------------------------------------------

# Effective wavelengths (Angstroms) for LSST filters
FILTER_WAVELENGTHS = {
    'u': 3641, 
    'g': 4704, 
    'r': 6155, 
    'i': 7504, 
    'z': 8695, 
    'y': 10056
}

# -----------------------------------------------------------------------------
# 5. TRAINING HYPERPARAMETERS
# -----------------------------------------------------------------------------

MODEL_CONFIG = {
    'default_model': 'logistic_regression',  # Options: 'logistic_regression', 'random_forest'
    'random_seed': 42,
    'test_size': 0.2
}
