'''
config.py
Author: maia.advance, maymeridian
Description: Centralized configuration for paths, model parameters, and physical constants.
'''

import os

# -----------------------------------------------------------------------------
# 1. PROJECT STRUCTURE
# -----------------------------------------------------------------------------

# Primary directories
SRC_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(SRC_DIR)
DATA_DIR = os.path.join(BASE_DIR, 'datasets')
MODELS_DIR = os.path.join(BASE_DIR, 'models')
PLOTS_DIR = os.path.join(BASE_DIR, 'plots')
PREDICTIONS_DIR = os.path.join(BASE_DIR, 'predictions')

# Ensure essential directories exist immediately
for directory in [DATA_DIR, MODELS_DIR, PREDICTIONS_DIR, PLOTS_DIR, BASE_DIR, SRC_DIR]:
    os.makedirs(directory, exist_ok=True)

# -----------------------------------------------------------------------------
# 2. DATA PATHS (ABSOLUTE)
# -----------------------------------------------------------------------------

# Logs (Metadata)
TRAIN_LOG_PATH = os.path.join(DATA_DIR, 'log_data/train_log.csv')
TEST_LOG_PATH = os.path.join(DATA_DIR, 'log_data/test_log.csv')

# Processed/Combined Data (The "All" files generated by data_loader)
TRAIN_DATA_PATH = os.path.join(DATA_DIR, 'combined_curves/train_all_full_lightcurves.csv')
TEST_DATA_PATH = os.path.join(DATA_DIR, 'combined_curves/test_all_full_lightcurves.csv')

PROCESSED_TRAINING_DATA_PATH = os.path.join(DATA_DIR, 'processed_data/processed_training_data.csv')
PROCESSED_TESTING_DATA_PATH = os.path.join(DATA_DIR, 'processed_data/processed_testing_data.csv')

# -----------------------------------------------------------------------------
# 3. MODEL ARTIFACTS
# -----------------------------------------------------------------------------

# The active production model
MODEL_PATH = os.path.join(MODELS_DIR, 'tde_classifier.pkl')

# Score tracking
SCORE_PATH = os.path.join(MODELS_DIR, 'latest_score.txt')

# -----------------------------------------------------------------------------
# 4. SCIENCE & PHYSICS CONSTANTS
# -----------------------------------------------------------------------------

# Effective wavelengths (Angstroms) for LSST filters
FILTER_WAVELENGTHS = {
    'u': 3641,
    'g': 4704,
    'r': 6155,
    'i': 7504,
    'z': 8695,
    'y': 10056
}

# -----------------------------------------------------------------------------
# 5. TRAINING HYPERPARAMETERS
# -----------------------------------------------------------------------------

MODEL_CONFIG = {
    'default_model': 'catboost',
    'random_seed': 67,
    'test_size': 0.2
}
